version: "3.9"

services:
  srv-postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "6432:5432"
    volumes:
      - vol-postgres:/var/lib/postgresql/data
    networks:
      - net-transcendence
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  srv-backend:
    container_name: backend
    image: backend:1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - net-transcendence
    volumes:
      - vol-profiles:/app/profiles
    depends_on:
      - srv-postgres
    environment:
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
      FT_OAUTH_CLIENT_ID: ${FT_OAUTH_CLIENT_ID}
      FT_OAUTH_CLIENT_SECRET: ${FT_OAUTH_CLIENT_SECRET}
      FT_OAUTH_REDIRECT_URI: ${FT_OAUTH_REDIRECT_URI}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      GOOGLE_OAUTH_REDIRECT_URI: ${GOOGLE_OAUTH_REDIRECT_URI}

  srv-frontend:
    container_name: frontend
    image: frontend:1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - vol-react_app:/app/dist
    environment:
      FT_OAUTH_CLIENT_ID: ${FT_OAUTH_CLIENT_ID}
      FT_OAUTH_REDIRECT_URI: ${FT_OAUTH_REDIRECT_URI}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_REDIRECT_URI: ${GOOGLE_OAUTH_REDIRECT_URI}

  srv-nginx:
    container_name: nginx
    image: nginx:1.0
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - net-transcendence
    volumes:
      - vol-react_app:/usr/share/nginx/html
      - vol-images:/usr/share/nginx/images
      - vol-profiles:/usr/share/nginx/profiles
    depends_on:
      - srv-backend
      - srv-frontend

networks:
  net-transcendence:
    name: transcendence

volumes:
  vol-postgres:
    name: postgres

  vol-react_app:
    name: react_app

  vol-images:
    name: images
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/share/images

  vol-profiles:
    name: profiles
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/share/profiles
