FROM nginx:latest

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf
# Copy the configuration into the container at /etc/nginx
COPY nginx.dev.conf /etc/nginx/conf.d/
COPY favicon.ico /usr/share/nginx/

ENTRYPOINT ["nginx", "-g", "daemon off;"]
